config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  resources :pages, only: [:index, :show]
  
  
  resources :settings, only: [:index]
  resources :details, only: [:index]
  resources :projects
  resources :contacts, only: [:index]
  resources :messages, only: [:new, :create]
  resources :links, only: [:index, :show]

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/navigation_link.rb
class NavigationLink < ApplicationRecord
  has_many :children, class_name: "NavigationLink", foreign_key: "parent_id", dependent: :destroy
  belongs_to :parent, class_name: 'NavigationLink', optional: true
  belongs_to :user, class_name: 'User'

  def file
    [file_name, file_type].join('.')
  end

  def self.nav_links(user)
    user_links = self.where(user_id: user)
    links = {
      :navbar => user_links
                 .sort_by { |link| link.container_order }
                 .select { |link| !link.parent_id }
    }
    
    links[:navbar].each { |nav_link|
      links[:page_links] ||= {}
      links[:page_links][nav_link.description] ||= user_links.select { 
        |link| link[:parent_id] == nav_link.id
      }
    }
    return links
  end

  def self.page_links(user)
    self.nav_links(user)[:page_links]
  end

end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :profile_photo
  has_one_attached :avatar
  has_one_attached :resume
  has_many :navigation_links, class_name: "NavigationLink",
  dependent: :destroy
  has_many :projects,
  class_name: "Project",
  dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

end

app/controllers/details_controller.rb
class DetailsController < ApplicationController

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :check_for_form, :check_for_projects

  def show
    @user = User.find(params[:user])
  end

  def check_for_form
    if params[:id] == "Contact Form"
      redirect_to new_message_path :position => params[:position]
    end
  end

  def check_for_projects
    redirect_to projects_path :position => params[:position]
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
  end

  def create
    puts "MessagesController#create => params: #{params}"
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    user = 1
    @navigation_links = NavigationLink.nav_links(user)
  end

  def show
    user = 1
    nav_links = NavigationLink.nav_links(user)
    index = nav_links[:navbar].find_index {
      |link| link.description == params[:id]
    }
    current_page = nav_links[:navbar].slice!(index)
    if index.even?
      nav_links[:navbar].unshift(current_page)
    else
      nav_links[:navbar].push(current_page)
    end
    @user = User.find(user)
    @navigation_links = nav_links
    @position = index.even? ? "top" : "bottom"
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
    
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.fetch(:project, {})
    end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def embedded_svg(filename, options = {})
    assets = Rails.application.assets
    asset = assets.find_asset(filename)

    if asset
      file = asset.source.force_encoding("UTF-8")
      doc = Nokogiri::HTML::DocumentFragment.parse file
      svg = doc.at_css "svg"
      svg["class"] = options[:class] if options[:class].present?
    else
      doc = "<!-- SVG #{filename} not found -->"
    end

    raw doc
  end

end

app/helpers/links_helper.rb
module LinksHelper

  def get_turbo_frame_name(frame_name)
    convert_title_to_snake_case(frame_name) + "_frame"
  end

  def get_turbo_links_frame_name(link_name)
    convert_title_to_snake_case(link_name) + "_links_frame"
  end

  def get_description_title_case(description_snake_case)
    description_title_case = convert_snake_to_title_case(description_snake_case)
    description_title_case.to_s
  end

  def get_page_link_id(link_name, page, position)
    return "#{convert_title_to_snake_case link_name}_#{convert_title_to_snake_case page}_#{position}"
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper

  def get_offset_distance(height, skew_x)
    radians = skew_x * Math::PI / 180
    offset = Math.tan(radians)
    offset_distance = height * offset
  end

  def get_container_height(container, total_containers)
    middle = total_containers / 2
    height = (middle - container) * 40
  end

  def get_container_position(container_pos, total_containers, skew_x, right)
    left = "left: 5vw"

    if right
      height = get_container_height(container_pos, total_containers) - 10
      offset_distance = "#{get_offset_distance(height/2, skew_x)}vh"
      left_calc = "calc(55vw + #{offset_distance})"
      left = "left: #{left_calc}"
      width = "width: calc(95vw - #{left_calc})"
      padding = "padding-left: 1vw"
    else
      height = get_container_height(container_pos, total_containers) + 10
      offset_distance = "#{get_offset_distance(height/2, skew_x)}vh"
      width = "width: calc(40vw + #{offset_distance})"
      padding = "padding-right: 1vw"
    end
    style = "#{left}; #{width}; #{padding}"
  end

  def get_navbar_position(position)
    class_name = position.nil? ? "" : "container__nav__#{position}"
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/strings_helper.rb
module StringsHelper

  def convert_title_to_snake_case(title_case)
    title_case.gsub(" ", "_").downcase
  end

  def convert_snake_to_title_case(snake_case)
    snake_case.gsub("_", " ").titleize
  end

  def convert_title_to_kebab_case(title_case)
    title_case.gsub(" ", "-").downcase
  end

end

app/views/details/index.html.erb
<%= turbo_frame_tag "links_description_frame" do %>
  <div class="container__link__<%= params[:position] %>">
    About view
  </div>
<% end %>

app/views/links/content/links/_github.html.erb
<h1>Github</h1>

app/views/links/content/links/_linkedin.html.erb
<h1>LinkedIn</h1>

app/views/links/content/links/_stack_overflow.html.erb
<h1>Stack Overflow</h1>

app/views/links/content/settings/_login.html.erb
<h1>Login</h1>

app/views/links/show.html.erb
<%= turbo_frame_tag "links_description_frame" do %>
  <div class="container__link__<%= params[:position] %>">
    <% link = convert_title_to_snake_case params[:id] %>
    <% page = convert_title_to_snake_case params[:page] %>
    <%= render "links/content/#{page}/#{link}" %>
  </div>
<% end %>

app/views/messages/create.html.erb
<%= turbo_frame_tag "links_description_frame" do %>
  <div class="container__link__<%= params[:position] %>">
    <div class="form">
      Thanks, I'll get back to you as soon as I can.
    </div>
  </div>
<% end %>

app/views/messages/new.html.erb
<%= turbo_frame_tag "links_description_frame" do %>
  <div class="container__link__<%= params[:position] %>">
    <%= form_with model: Message.new, class: "form" do |form| %>
      <table>
        <thead class="form__title">
          <th colspan='2'>
            Contact me
          </th>
        </thead>
        <tbody>
          <tr class='form__row'>
            <td class='form__label'>
              <%= form.label :first_name %>
            </td>
            <td>
              <%= form.text_area :first_name%>
            </td>
          </tr>
          <tr class='form__row'>
            <td>
              <%= form.label :name %>
            </td>
            <td>
              <%= form.text_area :name %>
            </td>
          </tr>
          <tr class='form__row'>
            <td>
              <%= form.label :email %>
            </td>
            <td>
              <%= form.email_field :email %>
            </td>
          </tr>
          <tr class='form__row'>
            <td>
              <%= form.label :phone %>
            </td>
            <td>
              <%= form.telephone_field :phone %>
            </td>
          </tr>
          <tr class='form__row'>
            <td>
              <%= form.label :subject %>
            </td>
            <td>
              <%= form.text_area :subject %>
            </td>
          </tr>
          <tr class='form__message'>
            <td colspan='2'>
              <%= form.text_area :body %>
            </td>
          </tr>
          <tr>
            <td colspan='2'>
              <%= form.submit "Send" %>
            </td>
          </tr>
          </tbody>
        </table>
        <%= hidden_field_tag :position, params[:position] %>
    <% end %>
<% end %>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div class="projects__card__header">
  <%= project.name %>
</div>
<div class="projects__card__body">
  <%= project.description %>
</div>
<div class="projects__card__footer">
  <%= link_to "Show this project", project %>
</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<%= turbo_frame_tag "links_description_frame" do %>
  <div class="container__link__<%= params[:position] %>">
    <div id="projects" class="projects">
      <% @projects.each do |project| %>
        <div id="<%= dom_id project %>" class="projects__card">
          <%= render project %>
        </div>
      <% end %>
    </div>
  </div>

  <%= link_to "New project", new_project_path %>

<% end %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>